controller_list:
  - name: fake_iiwa_green_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - iiwa_orange_joint_1
      - iiwa_orange_joint_2
      - iiwa_orange_joint_3
      - iiwa_orange_joint_4
      - iiwa_orange_joint_5
      - iiwa_orange_joint_6
      - iiwa_orange_joint_7
initial:  # Define initial robot poses per group
#  - group: iiwa_green_arm
#    pose: home

  []