controller_list:
  - name: iiwa_green_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - iiwa_orange_joint_1
      - iiwa_orange_joint_2
      - iiwa_orange_joint_3
      - iiwa_orange_joint_4
      - iiwa_orange_joint_5
      - iiwa_orange_joint_6
      - iiwa_orange_joint_7